### ISSUE TITLE
pyBigWig values method does not take argument numpy=True

### ISSUE THREAD

**Issue by tanjimin** [MiraldiLab/maxATAC#117]
https://github.com/MiraldiLab/maxATAC/blob/83cd5d2b95037cb2b100f72c0545e244336de72c/maxatac/utilities/normalization_tools.py#L47

```bash
  File "/gpfs/home/.conda/envs/maxatac/lib/python3.9/site-packages/maxatac/utilities/genome_tools.py", line 236, in chromosome_blacklist_mask
    return blacklist_bigwig_stream.values(chromosome,
TypeError: values() takes no keyword arguments
```

Same format in another file:
https://github.com/MiraldiLab/maxATAC/blob/83cd5d2b95037cb2b100f72c0545e244336de72c/maxatac/utilities/genome_tools.py#L239

Removing numpy=True seems to resolve the issue.

**Comment by tacazares** [comment]
Hey @tanjimin, 
This is a known issue, https://github.com/MiraldiLab/maxATAC/issues/87 , that is due to the inability of pybigwig to recognize that your system has numpy installed. Try some of the suggested tips, I am not sure how removing the `numpy=True` fix will affect the import of values/downstream processes.
Take care, 
Tareian
